window.requestFileSystem||(window.requestFileSystem=window.webkitRequestFileSystem);window.BlobBuilder||(window.BlobBuilder=window.WebKitBlobBuilder);
Registry.require("promise layout xmlhttprequest convert crcrc curtain layout/default/tabview layout/default/htmlutil helper i18n parser statistics layout/default/layout_helper".split(" "),function(){var K=rea.FEATURES,B=Registry.get("promise"),m=Registry.get("crcrc").cr,c=Registry.get("crcrc").crc,h=Registry.get("i18n"),C=Registry.get("curtain"),u=Registry.get("helper"),L=Registry.get("layout/default/tabview"),v=Registry.get("layout/default/htmlutil"),V=Registry.get("statistics"),F=Registry.get("layout"),
M=Registry.get("layout/default/layout_helper"),y=M.images;F.render(function(){M.addStyle();var k=null,t={},N="???",D=null,O="0.0.0",z=function(){var a=document.getElementById("ask"),b=c("div","content_wrapper","ask","main");if(a){var e=a.parentNode;e.removeChild(a);e.appendChild(b);$(document.body).addClass("main")}var a=c("div","head_container","ask","head_container"),e=c("div","tv_container_fit","ask","tv_container"),d=m("a","head_link","ask","head_link");d.href="http://tampermonkey.net";d.target=
"_blank";var f=c("div","float","ask","head1"),g=c("img","banner","ask");g.src=rea.extension.getURL("images/icon128.png");var h=c("div","float head","ask","head2"),l=c("div","header_title","heading"),n=c("div","version","version","version");n.textContent=" by Jan Biniok";var E=m("div","search","box","");l.textContent="Tampermonkey";f.appendChild(g);h.appendChild(l);h.appendChild(n);d.appendChild(f);d.appendChild(h);a.appendChild(d);a.appendChild(E);b.appendChild(a);b.appendChild(e);b=L.create("_main",
e);a=m("div","main","main","tab_content_h");a.textContent=N;e=m("div","main","main","tab_content");b.appendTab(u.createUniqueId("main","main"),a,e).select();C.hide();return e},W=function(a){var b=a.script,e=a.oldscript,d=c("div","viewer_bottom_tab","bottom","");a={tv:"tv tv_alt",tv_table:"tv_table tv_table_alt",tr_tabs:"tr_tabs tr_tabs_alt",tr_content:"tr_content tr_content_alt",td_content:"td_content td_content_alt",td_tabs:"td_tabs td_tabs_alt",tv_tabs_align:"tv_tabs_align tv_tabs_align_alt",tv_tabs_fill:"tv_tabs_fill tv_tabs_fill_alt",
tv_tabs_table:"tv_tabs_table tv_tabs_table_alt",tv_contents:"tv_contents tv_contents_alt",tv_tab_selected:"tv_tab tv_selected tv_tab_alt tv_selected_alt",tv_tab_close:"",tv_tab:"tv_tab tv_tab_alt",tv_content:"tv_content tv_content_alt"};if(t.editor_enabled){var f=L.create("_source"+b.uuid,d,a),g,p=function(b,a){var d=c("div","tv_content tv_content_alt",b.uuid,a+"container_o"),e=c("table","editor_container_o editor_400p_container_o p100100 noborder",b.uuid,a+"container_o"),g=c("tr","editor_container p100100",
b.uuid,a+"container");d.appendChild(e);e.appendChild(g);var e=c("td","editor_outer editor_400p_outer",b.uuid,a+"edit"),f=c("div","editor_100 editor_border",b.uuid,a+"edit");g.appendChild(e);e.appendChild(f);return{c:d,e:f}},l=function(){var b=B();F.addStyle("vendor/cm/mode/diff/diff.css");Registry.vendor(["vendor/jsdiff/diff","vendor/cm/mode/diff/diff"],function(){l=B.Pledge;b.resolve()});return b.promise()};(function(){return e?l().then(function(){var a=m("div",b.uuid,"diff_h");a.textContent=h.getMessage("Changes");
var c=p(b,"diff");d.diff=new MirrorFrame(c.e,{theme:"diff",fontSize:t.editor_fontSize,value:h.getMessage("Please_wait___"),noButtons:!0,mode:"diff",readOnly:!0});g=f.appendTab("diff",a,c.c,function(){window.setTimeout(function(){d.diff.refresh();d.diff.mirror.focus()},1)});window.setTimeout(function(){var a;try{a=window.JsDiff.createTwoFilesPatch(h.getMessage("Current_Version"),h.getMessage("New_Version"),e.textContent,b.textContent,void 0,void 0,{timeout:4E3})}catch(c){console.warn(c)}a||(a=h.getMessage("The_diff_for_this_script_is_too_large_to_render"));
d.diff.mirror.setValue(a)},500)}):B.Pledge()})().then(function(){var a=m("div",b.uuid,"source_h");a.textContent=h.getMessage("Source_Code");var c=p(b,"source");d.editor=new MirrorFrame(c.e,{theme:t.editor_theme,fontSize:t.editor_fontSize,value:b.textContent,noButtons:!0,matchBrackets:!0,readOnly:!0});a=f.appendTab("source",a,c.c,function(){window.setTimeout(function(){d.editor.refresh();d.editor.mirror.focus()},1)});g=g||a}).then(function(){g.select()})}else{var n=c("div","editor_400p_outer","editor",
b.name);a=c("div","editor_400p editor_border","editor",b.name);d.appendChild(n);n.appendChild(a);n=c("textarea","editorta","editor",b.name);n.setAttribute("wrap","off");a.appendChild(n);n.value=b.textContent}return d},X=function(){var a={};window.addEventListener("keydown",function(b){var c=!1;if("keydown"==b.type&&(a[b.keyCode]&&(c=a[b.keyCode](b)),c))return b.stopPropagation(),b.preventDefault(),!1},!0);return{registerListener:function(b,c){a[b]=c}}}(),w=function(a,b,e){u.select(e,function(a){return a.label}).forEach(function(d){var e=
c("button",b,"tm",d.label);d.id&&e.setAttribute("data-btn-id",d.id);if(d.icon){var g=m("img","tm",d.label,d.icon);g.src=y.get(d.icon);g.setAttribute("height","24px");e.appendChild(g)}g=m("span","tm",d.label,"label");g.textContent=d.label;e.appendChild(g);e.addEventListener("click",d.fn);a.appendChild(e);d.focus&&window.setTimeout(function(){$(e).focus()},300);d.keyDown&&X.registerListener(d.keyDown.keyCode?d.keyDown.keyCode:d.keyDown,d.keyDown.cb?d.keyDown.cb:d.fn)})},Z=function(a){var b=a.script,
e=c("div","viewer_last","install"),d=c("div","viewer_content","install_content"),f=c("div","ask_action_buttons","install_buttons"),g=[];g.push({label:a.messages.action,fn:function(){q(k.aid,"install")},focus:!0});K.RUNTIME.CHROME&&21>K.RUNTIME.BROWSER_VERSION&&g.push({label:a.messages.flags.install?h.getMessage("Process_with_Chrome"):null,fn:function(){Y(b.fileURL);$(e).hide()}});g.push({label:h.getMessage("Cancel"),fn:x,keyDown:27});w(f,"install",g);d.appendChild(f);e.appendChild(d);return e},aa=
function(a){var b=c("div","viewer_last","import"),e=c("div","viewer_content","import_content"),d=c("div","ask_action_buttons import_buttons","import_buttons");w(d,"import",[{label:h.getMessage("Import"),fn:function(){var b=Object.keys(a.scripts).filter(function(a){return!!$("input[type=checkbox][data-import-id="+a+"]:checked").val()}),c=a.global_settings&&!!$("input[type=checkbox][data-import-id=global_settings]:checked").val();q(k.aid,"import",{data:{import_ids:b,global_settings:c}})},focus:!0},
{label:h.getMessage("Cancel"),fn:x,keyDown:27}]);e.appendChild(d);b.appendChild(e);e=c("div","section","btn");e.appendChild(b);return e},ba=function(a){a=c("div","viewer_last","ok");var b=c("div","viewer_content","ok_content"),e=c("div","ask_action_buttons","ok_buttons");w(e,"import",[{label:h.getMessage("Ok"),fn:x,focus:!0}]);b.appendChild(e);a.appendChild(b);return a},ca=function(a,b){var e=c("div","viewer_last","ok"),d=c("div","viewer_content","ok_content"),f=c("div","ask_action_buttons","ok_buttons");
w(f,"permission",[{label:h.getMessage("Ok"),fn:function(){rea.permissions.request({permissions:[b.permission]},function(a){rea.runtime.lastError&&console.warn("notify: error on getting permission",b.permission+"!","reason:",rea.runtime.lastError.message);q(k.aid,"permission",{data:{granted:a,permission:b.permission}})})},focus:!0},{label:h.getMessage("Cancel"),fn:x,keyDown:27}]);d.appendChild(f);e.appendChild(d);var d=c("div","viewer_upper","permission"),f=c("div","viewer_info viewer_info_wide","general",
"permission"),g=c("div","viewer_content","general_content","permission"),p=m("h3","install","heading","permission"),l=c("span","message","heading","permission");p.textContent=b.title;l.textContent=b.message;g.appendChild(l);f.appendChild(p);f.appendChild(g);d.appendChild(f);f=c("div","section","perm_src","permission");f.appendChild(d);f.appendChild(e);a.appendChild(f)},ea=function(a,b){var e=Date.now(),d,f;b.timeout&&(d=window.setTimeout(function(){x();g()},b.timeout));var g=function(){var a;f&&window.clearInterval(f);
d&&window.clearTimeout(d);f=d=null;(a=$("button[data-btn-id]")[0])&&a.parentNode.removeChild(a)},p=c("div","viewer_last","ok"),l=c("div","viewer_content","ok_content"),n=c("div","ask_action_buttons","ok_buttons"),E=c("div","ask_action_buttons","ok_buttons"),r=c("div","ask_action_buttons","ok_buttons");w(n,"connect",[{label:h.getMessage("Allow_once"),icon:"button_ok",fn:function(){return q(k.aid,"connect",{data:{ok:!0,allow:!0,once:!0}})},focus:!0},{label:h.getMessage("Temporarily_allow"),icon:"clock",
fn:function(){return q(k.aid,"connect",{data:{ok:!0,allow:!0,temporary:!0}})}},{label:b.hostname!=b.domain?h.getMessage("Always_allow"):h.getMessage("Always_allow_domain"),icon:"edit_add",fn:function(){return q(k.aid,"connect",{data:{ok:!0,allow:!0}})}},function(){return b.hostname!=b.domain?{label:h.getMessage("Always_allow_domain"),icon:"edit_add",fn:function(){return q(k.aid,"connect",{data:{ok:!0,allow:!0,whole_domain:!0}})}}:null}(),function(){return b.all_domains?{label:h.getMessage("Always_allow_all_domains"),
icon:"critical",fn:function(){g();if(window.confirm(h.getMessage("This_gives_this_script_the_permission_to_retrieve_and_send_data_from_and_to_every_webpage__This_is_potentially_unsafe__Are_you_sure_you_want_to_continue_")))return q(k.aid,"connect",{data:{ok:!0,allow:!0,all_domains:!0}})}}:null}()].filter(function(a){return a}));w(E,"connect",[{label:h.getMessage("Forbid_once"),icon:"cancel",fn:function(){return q(k.aid,"connect",{data:{ok:!0,deny:!0,once:!0}})},keyDown:27},{label:b.hostname!=b.domain?
h.getMessage("Always_forbid"):h.getMessage("Always_forbid_domain"),icon:"no",fn:function(){return q(k.aid,"connect",{data:{ok:!0,deny:!0}})}},function(){return b.hostname!=b.domain?{label:h.getMessage("Always_forbid_domain"),icon:"no",fn:function(){return q(k.aid,"connect",{data:{ok:!0,deny:!0,whole_domain:!0}})}}:null}(),{label:h.getMessage("Dont_ask_again"),icon:"exit",fn:function(){return q(k.aid,"connect",{data:{ok:!0,deny:!0,all_domains:!0}})}}].filter(function(a){return a}));w(r,"connect_misc",
[function(){return b.tabid?{label:h.getMessage("Focus_tab"),icon:"windowlist",fn:function(){da("focus_tab",{tabid:b.tabid})}}:null}(),function(){if(b.timeout)return f=window.setInterval(function(){var a;(a=$("button[data-btn-id]")[0])&&$(a).find("span").text(h.getMessage("Skip_timeout__0seconds0_seconds_",Math.round((b.timeout+e-Date.now())/1E3)))},1E3),{label:h.getMessage("Skip_timeout__0seconds0_seconds_",Math.round(b.timeout/1E3)),id:"skip_timeout_button",fn:g}}()].filter(function(a){return a}));
var v=c("div","viewer_upper","connect"),G=c("div","viewer_info viewer_info_wide","general","connect"),t=c("div","viewer_content","general_content","connect"),H=m("h3","install","heading","connect"),P=c("span","message","heading","connect");if(b.script.icon){var A=m("img","version","heading","connect");A.src=b.script.icon;H.appendChild(A)}H.textContent=h.getMessage("A_userscript_wants_to_access_a_cross_origin_resource_");var A=c("div","ask_action_buttons message","help","connect"),Q=m("div","help",
"connect"),I=h.getMessage("A_request_to_a_cross_origin_resource_is_nothing_unusual__You_just_have_to_check_whether_this_script_has_a_good_reason_to_access_this_domain__For_example_there_are_only_a_very_few_reasons_for_a_userscript_to_contact_your_bank__Please_note_that_userscript_authors_can_avoid_this_dialog_by_adding_@connect_tags_to_their_scripts__You_can_change_your_opinion_at_any_time_at_the_scripts_settings_tab_",b.connect_url,b.settings_url),I=I.replace(/>/g,"&gt;").replace(/</g,"&lt;").replace(/\[url=([^\]]+)\](.*)\[\/url\]/g,
'<a target="_blank" href="$1">$2 &#x2B00;</a>').replace(/\n/g,"<br>");Q.innerHTML=I+"<br><br>";A.appendChild(Q);l.appendChild([r,A,n,E]);p.appendChild(l);var R=c("table","script_desc","connect");[{prop:"name",label:h.getMessage("Name")},{prop:"src_url",label:h.getMessage("Tab_URL")},{prop:"hostname",label:h.getMessage("Destination_domain")},{prop:"url",label:h.getMessage("Destination_URL")}].forEach(function(a){var e=b[a.prop]||b.script[a.prop]||a.value,d=c("tr","script_desc",a.prop,"connect"),g=
c("td","script_desc",a.prop,"connectdt"),f=c("td","script_desc",a.prop,"connectdd");g.textContent=a.label?a.label:"";f.textContent=e||h.getMessage("_not_set_");d.appendChild(g);d.appendChild(f);R.appendChild(d)});P.appendChild(R);t.appendChild(P);G.appendChild(H);G.appendChild(t);v.appendChild(G);l=c("div","section","connect_src","connect");l.appendChild(v);l.appendChild(p);a.appendChild(l)},ga=function(a,b){a.appendChild(aa(b));if(b.global_settings){var e=c("div","viewer_upper","");fa({content:e,
checkbox:"import",key:"global_settings"});a.appendChild(e)}b.scripts&&Object.keys(b.scripts).forEach(function(e){var f=b.scripts[e],g=c("div","viewer_upper",e);J({content:g,preparat:f,checkbox:"import",key:e},!0);a.appendChild(g)})},S=function(a,b){var c=m("input",a+"_",b,"",!0);c.setAttribute("data-import-id",b);c.checked=!0;c.type="checkbox";c.addEventListener("click",function(a){(a.ctrlKey||a.metaKey)&&$("input[type=checkbox][data-import-id!="+b+"]").prop("checked",c.checked)});return c},fa=function(a){var b=
a.key,e=a.content,d=c("div","viewer_upper",b),f=c("div","viewer_info viewer_info_wide","general",b),g=c("div","viewer_content","general_content",b),p=m("h3","install","heading",b);a.checkbox&&p.appendChild(S(a.checkbox,a.key));a=m("img","version","heading",b);a.src=rea.extension.getURL("images/icon128.png");p.appendChild(a);a=m("span","name","heading",b);a.textContent=h.getMessage("Global_Settings");p.appendChild(a);f.appendChild(p);p=c("table","script_desc",b);a=c("tr","settings_desc","action",b);
var l=c("td","settings_desc","action",b+"dt"),n=c("td","settings_desc","action",b+"dd");l.textContent=h.getMessage("Action");n.textContent=h.getMessage("Global_settings_import");a.appendChild(l);a.appendChild(n);p.appendChild(a);a=c("tr","settings_desc","warning",b);l=c("td","settings_desc","warning",b+"dt");n=c("td","settings_desc","warning",b+"dd");l.innerHTML='<img src="'+y.get("critical")+'"></img>&nbsp;';n.textContent=h.getMessage("This_will_overwrite_your_global_settings_");a.appendChild(l);
a.appendChild(n);p.appendChild(a);g.appendChild(p);f.appendChild(g);d.appendChild(f);b=c("div","section","settings_src");b.appendChild(d);e.appendChild(b)},J=function(a,b){var e=a.preparat,d=a.content,f=e.script||{},g=f.uuid||f.id||f.name;e.short_info||(e.short_info=[]);var p=c("div","viewer_upper",g),l=c("div","viewer_info "+(b?"viewer_info_wide":"viewer_info_multiple"),"general",g),n=c("div","viewer_content","general_content",g),k=m("h3","install","heading",g);a.checkbox&&k.appendChild(S(a.checkbox,
a.key));if(f.icon||f.icon64){var r=m("img","version","heading",g);r.src=f.icon||f.icon64;k.appendChild(r)}r=m("span","name","heading",g);r.textContent=e.heading||f.name||"";k.appendChild(r);f.version&&(r=c("span","view_version","heading",g),r.textContent="v"==f.version[0]?"":"v",r.textContent+=f.version,k.appendChild(r));l.appendChild(k);b&&e.short_info.unshift({prop:"heading",value:e.messages.heading,label:h.getMessage("Action")});var q=c("table","script_desc",g);e.short_info.forEach(function(a){var e=
f[a.prop]||a.value;if(e||!b){var d=c("tr","script_desc",a.prop,g),l=c("td","script_desc",a.prop,g+"dt"),k=c("td","script_desc",a.prop,g+"dd");l.textContent=a.label?a.label:"";k.textContent=e||h.getMessage("_not_set_");d.appendChild(l);d.appendChild(k);q.appendChild(d)}});n.appendChild(q);var k=c("div","viewer_info viewer_info_multiple","info",g),t;b?t=n:(t=c("div","viewer_content","info_content",g),r=m("h4","action","heading",g),r.textContent=e.messages.heading,t.appendChild(r));var u=0;["errors",
"warnings","info"].forEach(function(a){var b=m("table",a,g+u);(e.messages[a]||[]).forEach(function(c){u++;var e=m("tr",a,g+u),d=m("td",a,g+"dt"+u),f=m("td",a,g+"dd"+u);"info"==a?c.label&&c.value?(d.textContent=c.label,f.textContent=c.value):(d.innerHTML='<img src="'+y.get("info")+'"></img>&nbsp;',f.innerHTML=v.safeTagsReplace(c).replace(/\n/,"<br />")):"warnings"==a?(d.innerHTML='<img src="'+y.get("critical")+'"></img>&nbsp;',f.innerHTML=v.safeTagsReplace(c).replace(/\n/,"<br />")):"errors"==a&&(d.innerHTML=
'<img src="'+y.get("error")+'"></img>&nbsp;',f.innerHTML=v.safeTagsReplace(c).replace(/\n/,"<br />"));e.appendChild(d);e.appendChild(f);b.appendChild(e)});t.appendChild(b)});r=function(a,b,e,d){var l=m("table",a,g),k=0,p={};b.forEach(function(b){if(!(k>d||p[b])){p[b]=!0;var f=c("tr",a+"desc",b,g+k),h=c("td",a+"desc",b,g+k+"dt"),m=c("td",a+"desc",b,g+k+"dd");h.innerHTML=0==k?v.safeTagsReplace(e.label):"&nbsp;";m.innerHTML=k==d?'<span title="'+v.safeTagsReplace(e.warning)+'">...!</span>':v.safeTagsReplace(b);
f.appendChild(h);f.appendChild(m);l.appendChild(f);k++}});if(f.options&&(b=f.options.override&&f.options.override["use_"+a])&&b.length){b=c("tr",a+"desc","ovverride",g+k);var n=c("td",a+"desc","ovverride",g+k+"dt"),q=c("td",a+"desc","ovverride",g+k+"dd");n.innerHTML=0==k?v.safeTagsReplace(e.label):"&nbsp;";q.innerHTML=v.safeTagsReplace(" ("+h.getMessage("overwritten_by_user")+")");b.appendChild(n);b.appendChild(q);l.appendChild(b)}t.appendChild(l)};r("includes",(f.includes||[]).concat(f.matches||
[]),{label:h.getMessage("Include_s__"),warning:h.getMessage("Attention_Can_not_display_all_includes_")},5);r("excludes",f.excludes||[],{label:h.getMessage("Exclude_s__"),warning:h.getMessage("Attention_Can_not_display_all_excludes_")},3);l.appendChild(n);k.appendChild(t);p.appendChild(l);p.appendChild(k);l=c("div","section",g,"install_src");l.appendChild(p);a.install&&l.appendChild(a.install(e));a.editor&&l.appendChild(a.editor(e));d.appendChild(l)},Y=function(a){q(k.aid,"abort");window.setTimeout(function(){window.location=
a+"#bypass=true"},10)},x=function(a){q(k.aid,"abort");window.setTimeout(function(){window.close()},3E3)},T=function(a,b){q(k.aid,"unload");D&&(window.clearInterval(D),D=null);window.removeEventListener("unload",T)};window.addEventListener("unload",T);var U=function(){window.location.search||window.location.hash?(k=u.getUrlArgs(),k.aid?(q(k.aid,"preparat",{layout:!0}).done(function(a){a.ext&&a.ext.version&&(O=a.ext.version);a.i18n&&h.setLocale(a.i18n);if(a.options&&(a.options.statistics_enabled&&V.init("ask",
O),a.options.layout_user_css)){var b=document.createElement("style");b.innerHTML=a.options.layout_user_css;(document.head||document.body||document.documentElement||document).appendChild(b)}N=h.getMessage("Install");b=null;a.preparat&&("install"==a.type?b=function(){J({content:z(),preparat:a.preparat,install:Z,editor:W})}:"install_error"==a.type?b=function(){J({content:z(),preparat:a.preparat,install:ba},!0)}:"import"==a.type?b=function(){ga(z(),a.preparat)}:"permission"==a.type?b=function(){ca(z(),
a.preparat)}:"connect"==a.type&&(b=function(){ea(z(),a.preparat)}),D=window.setInterval(ha,3E3),b&&window.setTimeout(b,1))}).fail(function(){x()}),C.wait(h.getMessage("Please_wait___"))):x()):window.onhashchange=function(){U()}},ha=function(){return q(k.aid,"ping",{bg:!0})},q=function(a,b,c){c=c||{};var d=B();try{var f={aid:a,method:b,layout:c.layout};c.data&&u.each(c.data,function(a,b){f[b]=c.data[b]});sendMessage({method:"askCom",data:f},function(a){c.bg||C.hide();t=a.options||t;c.layout&&a.layout&&
F.applyTheme(a.layout);a.error?(a.please_close&&window.setTimeout(window.close,100),d.reject(a)):d.resolve(a)});c.bg||C.wait(h.getMessage("Please_wait___"))}catch(g){console.warn("sS: "+g.message),d.reject()}return d.promise()},da=function(a,b,c){try{sendMessage(u.assign({method:"buttonPress",name:a},b),function(a){c&&c(a)})}catch(d){console.log("button: "+d.message)}};rea.extension.onMessage.addListener(function(a,b,c){t=a.options||t;if("confirm"==a.method)u.confirm(a.msg,function(a){c({confirm:a})});
else if("showMsg"==a.method)u.alert(a.msg),c({});else return!1;return!0});U()})});
