Registry.require(["crcrc","helper","layout/default/layout_helper"],function(){var l=Registry.get("crcrc").cr,k=Registry.get("crcrc").crc,q=Registry.get("helper"),u=Registry.get("layout/default/layout_helper").images,n=function(b,a,c){var d=(a.uuid?a.uuid:"")+a.id,e=l("div",a.name,d,"input");e.key=a.id;var f=l("input",a.name,d,"input",!0);b=b.split("##");f.name=a.name;f.uuid=a.uuid;f.key=a.id;f.oldvalue=a.value;f.value=void 0!=a.value?a.value:"";f.type="text";f.setAttribute("spellcheck","false");c&&
!f.inserted&&f.addEventListener("change",c);c=k("span","optiondesc",a.name,d,"s1");d=l("span",a.name,d,"s2");c.textContent=b[0]+":";1<b.length&&(d.textContent=b[1]);e.appendChild(c);e.appendChild(f);e.appendChild(d);a.enabledBy&&e.setAttribute("name","enabled_by_"+a.enabledBy);return{elem:e,input:f}},v=function(b,a,c){b=null;b=k("input","button",a.name,(a.uuid?a.uuid:"")+a.id,"bu",!0);b.name=a.name;b.uuid=a.uuid;b.key=a.id;b.type="button";b.value=a.name;b.data=a.data;b.reload=a.reload;b.ignore=a.ignore||
a.reload;b.warning=a.warning;a.enabledBy&&b.setAttribute("name","enabled_by_"+a.enabledBy);!b.inserted&&c&&b.addEventListener("click",c);return b},w=function(b,a,c,d){var e=null,e=k("input","button",b,a,"bu",!0);e.name=b;e.key=a;e.type="button";e.value=c;!e.inserted&&d&&e.addEventListener("click",d);return e},r=function(b,a){var c=(b.uuid?b.uuid:"")+b.id,d,e;if(e=b.after||b.validation)d=b.validation?"validation":"help",d=k("span",d,b.name,c,d,!0),e.imageURL&&(c=['background-image: url("'+e.imageURL+
'")'],e.opacity&&c.push("opacity: "+e.opacity),d.setAttribute("style",c.join(";"))),d&&(a&&d.addEventListener("click",a),e.msg&&d.setAttribute("title",e.msg));return d},x=function(b){return{"&":"&amp;","<":"&lt;",">":"&gt;"}[b]||b},p=function(b,a,c,d){var e=(d.uuid?d.uuid:"")+d.id;a.title=b;(b=r({after:{imageURL:u.get("help")},name:d.name,id:e}))&&c.appendChild(b)};Registry.register("layout/default/htmlutil","5549",{getInfoFromUrl:function(b){if(-1!=b.search(/\/\^?(http(s|s\?|\.\+)?|\.\*):\/\/(\.\*)*\$?\/?$/)||
-1!=b.search(/htt(ps|p):\/\/(\*\/\*|\*)*$/)||-1!=b.search(/\*:\/\/(\*\/\*|\*)*$/)||"*"==b)return{dom:"*",tld:"*"};0==b.search(/\//)&&(b=b.replace(/\([^\)]*\)[\?|\+|\*|\{[^\}]*]*/g,""),b=b.replace(/\[[^\]]*\][\?|\+|\*|\{[^\}]*]*/g,""),b=b.replace(/^\/|\/$|\^|\$|\\\?.*|#.*|\?|\(|\)|\+|\\|\.\*|/g,""));b=b.replace(/^\*:\/\//,"http://");0!=b.search("http")&&(b="http://"+b);b=b.split("/");if(3>b.length)return null;b=b[2].split(".");if(2>b.length)return null;var a=b[b.length-1],c=b[b.length-2];"*"!==c&&
(c=c.replace(/\*/g,""));for(var d=[],e=b.length-3;0<=e&&-1==b[e].search("\\*");e--)d.push(b[e]);return{tld:a,dom:c,subdom:d.reverse()}},getValue:function(b){var a=b.value;if("native"===b.valtype)if("undefined"===a)a=void 0;else if("null"===a)a=null;else try{a=JSON.parse(a)}catch(c){}return a},safeTagsReplace:function(b){return b.replace(/[&<>]/g,x)},addClass:function(b,a){var c=b.getAttribute("class")||"";-1==c.search(new RegExp("[ \t]*"+a+"[ \t]*"))&&(c=(c?c+" ":"")+a);b.setAttribute("class",c)},
toggleClass:function(b,a){var c=b.getAttribute("class")||"",d=new RegExp("[ \t]*"+a+"[ \t]*"),c=-1!=c.search(d)?c.replace(d,""):(c?c+" ":"")+a;b.setAttribute("class",c)},setHelp:p,createAfterIcon:r,createEnabler:function(b,a,c,d,e){var f=d.disabled,h=d.title,g=d.on||"ON",l=d.off||"OFF",m=k("div","slider-frame enabler "+b,a,c+"slider-frame",d.append,"wrap",!0);b=k("div","slider-button",a,c+"slider-button");d=k("div","on",a,c+"slider-button-enabled");var t=k("div","off",a,c+"slider-button-disbled");
d.textContent=g;t.textContent=l;m.appendChild(b);b.appendChild([d,t]);h&&(m.title=h);m.key=c;m.uuid=a;f||m.addEventListener("click",function(){$(m).hasClass("enabler_enabled")?$(m).removeClass("enabler_enabled"):$(m).addClass("enabler_enabled");e&&window.setTimeout(function(){e.call(m)},100)});return m},createImage:function(b,a,c,d,e,f){var h=k("img","icon16",a,c,d,!0);h.setAttribute("src",b);f&&(b=h.getAttribute("class")||"",h.setAttribute("class",b+" clickable"));h.alt=e?h.title=e:a||d||c;h.key=
c;h.name=a;f&&(h.addEventListener("click",f),h.href="#");return h},createFavicon:function(b,a,c,d){var e=k("img","icon16",a,c,q.filter(d,/[a-zA-Z0-9]/g));if(e.inserted)return e;"Array"!==q.toType(b)&&(b=[b]);c=function(){if(0!=b.length){var a=b.shift();e.setAttribute("src",a)}};e.addEventListener("error",c);c();e.alt=d?e.title=d:a;return e},createFileInput:function(b,a,c){b=k("input","import","file",null,null,!0);b.inserted||(b.type="file",c&&b.addEventListener("change",c));return b},createNamedSettings:function(b,
a,c){var d=(a.uuid?a.uuid:"")+a.id,e=k("div","settingsta",a.name,d,"named_wrapper"),f=k("div","named",a.name,d,"named_settings"),h=[],g=l("span",a.name,d,"s1");b&&(g.textContent=b+":");a.desc&&p(a.desc,g,g,a);e.appendChild(g);e.appendChild(f);e.key=a.id;a.value.forEach(function(b){var e=k("div","",a.name+b.name,d,"named",!0),g=k("div","",a.name+b.name,d,"named_label",!0);g.textContent=b.name;e.appendChild(g);g=l("textarea",a.name+b.name,d,"textarea",!0);g.setAttribute("spellcheck","false");g.name=
a.name;g.key=a.id;g.named_name=b.name;g.uuid=a.uuid;g.named=!0;g.oldvalue=b.value||"";g.value=b.value||"";c&&!g.inserted&&g.addEventListener("change",c);e.appendChild(g);f.appendChild(e);h.push(g)});return{elem:e,textareas:h,label:g}},createTextarea:function(b,a,c){var d=(a.uuid?a.uuid:"")+a.id,e=l("div",a.name,d,"textarea");e.key=a.id;var f=k("textarea","settingsta",a.name,d,"textarea",!0);f.setAttribute("spellcheck","false");f.name=a.name;f.key=a.id;f.uuid=a.uuid;f.array=a.array;f.oldvalue=a.value;
f.value=void 0!=a.value?a.array?a.value.join("\n"):a.value:"";c&&!f.inserted&&f.addEventListener("change",c);c=l("span",a.name,d,"s1");b&&(c.textContent=b+":");a.desc&&p(a.desc,c,c,a);e.appendChild(c);e.appendChild(f);return{elem:e,textarea:f,label:c}},createFileSelect:function(b,a,c){var d=(a.uuid?a.uuid:"")+a.id,e=l("input",a.name,d,"file"),f=function(a){c(a.target.files)};e.inserted||(e.type="file",e.addEventListener("change",f,!1));return b?(f=l("div",a.name,d,"input"),a=l("span",a.name,d,"s1"),
a.textContent=b+":",f.appendChild(a),f.appendChild(e),{elem:f,input:e}):{elem:e}},createInput:n,createColorChooser:function(b,a,c){var d=(a.uuid?a.uuid:"")+a.id;b=n(b,a,c);var e=function(){c&&c.apply(this,arguments);var a=(this.value.match(/[a-fA-F0-9]+/)||"")[0];a&&-1!=[3,6].indexOf(a.length)&&f.setAttribute("style","background-color: #"+a+";")};b.input.inserted||b.input.addEventListener("keyup",e);var f=k("span","color_choosed",a.name,d,"col");b.col=f;b.elem.appendChild(b.col);e.call(b.input);return b},
createPassword:function(b,a,c){b=n(b,a,c);b.input.setAttribute("type","password");return b},createCheckbox:function(b,a,c){var d=(a.uuid?a.uuid:"")+a.id,e=k("div","checkbox",a.name,d,"cb1");e.key=a.id;var f=l("input",a.name,d,"cb",!0);f.title=a.desc?a.desc:"";f.name=a.name;f.uuid=a.uuid;f.key=a.id;f.reload=a.reload;f.warning=a.warning;f.oldvalue=a.enabled;f.checked=a.enabled;f.type="checkbox";f.valtype="boolean";c&&!f.inserted&&f.addEventListener("click",c);c=k("span","checkbox_desc",a.name,d,"cb2");
c.textContent=b;a.desc&&p(a.desc,e,c,a);e.appendChild(f);e.appendChild(c);return{elem:e,input:f}},createDropDown:function(b,a,c,d,e){var f=(a.uuid?a.uuid:"")+a.id,h=l("div",a.name,f,"outer_dd");h.key=a.id;var g=l("select",a.name,f,"dd",!0),n=!1;c&&Object.keys(c).forEach(function(b){var d=l("option",a.name,c[b].name,"dd"+f,!0);d.textContent=q.decodeHtml(c[b].name);d.value=c[b].value;d.warning=c[b].warning;n|=!!c[b].warning;c[b].enabledBy&&d.setAttribute("name","enabled_by_"+c[b].enabledBy);a.enabler&&
c[b].enable&&d.setAttribute("enables",JSON.stringify(c[b].enable));c[b].value==a.value&&(d.selected=!0);g.appendChild(d)});g.key=a.id;g.name=a.name;g.uuid=a.uuid;g.reload=a.reload;g.warning=a.warning;g.oldvalue=a.value;g.valtype="native";g.inserted||(d&&g.addEventListener("change",d),n&&e&&g.addEventListener("change",e));null!==b&&(d=k("span","optiondesc",a.name,f,"inner_dd"),d.textContent=b+": ",h.appendChild(d));h.appendChild(g);a.desc&&p(a.desc,h,h,a);a.enabledBy&&h.setAttribute("name","enabled_by_"+
a.enabledBy);return{elem:h,select:g}},createImageButton:function(b,a,c,d,e){var f=null,h=null,g=null,f=k("button","imgbutton button",b,a,"bu",!0),h=k("div","imgbutton_container",b,a,"bu_container");h.appendChild(f);f.uuid=b;f.key=a;g=k("img","imgbutton_image",b,a,"bu_img",!0);g.src=d;f.appendChild(g);f.title=g.title=g.alt=c;!f.inserted&&e&&f.addEventListener("click",e);return h},createButton:function(b,a,c,d){return"Object"===q.toType(a)?v.apply(this,arguments):w.apply(this,arguments)},createPosition:function(b,
a,c){for(var d=(a.uuid?a.uuid:"")+a.id,e=l("div",a.name,d,"pos1"),f=l("select",a.name,d,"pos",!0),h=1;h<=a.posof;h++){var g=l("option",a.name,d,"opt"+h);g.textContent=h;h==a.pos&&(g.selected=!0);f.appendChild(g)}f.key=a.id;f.uuid=a.uuid;f.name=a.name;c&&!f.inserted&&f.addEventListener("change",c);a=k("span","optiondesc",a.name,d,"pos2");a.textContent=b;e.appendChild(a);e.appendChild(f);return e},createSearchBox:function(b){var a=k("div","searchbox","search_inner"),c=k("div","searchbox_mv","search_inner_mv"),
d=k("input","searchbox_input","search_input"),e=k("input","searchbox_button","search_button");d.type="text";d.setAttribute("spellcheck","false");d.value=b;e.type="button";e.value="Go";var f=function(){window.location=window.location.origin+window.location.pathname+"?url="+encodeURIComponent(d.value)};e.addEventListener("click",f);d.addEventListener("keyup",function(a){a&&13==a.keyCode&&f()});c.appendChild(d);c.appendChild(e);a.appendChild(c);return a},isScrolledIntoView:function(b,a){var c=$(b),d=
$(window),e=a&&a.padding||0,f=d.scrollTop(),d=f+d.height(),h=c.offset().top;return h+c.height()<=d-e&&h>=f+e}})});
